// const score = 400;
// console.log(score) 
//  // here it is a number but to spacifi that its a number
// const balance = new Number(121.894660);
// console.log(balance);// now spacifi that its a number

// console.log(balance.toString()) // now 100 is converted to Number to string(so, we can use every string function)
// // we can check the length of the string to 
// console.log(balance.toString().length) // here the length of string = 10011 is 5!
// console.log(balance.toString().split('0')) // output: [ '121.89466' ] which mean==>Number converted to string array
// console.log(balance.toFixed(3)); // 121.00  hrer toFixed(number) function limited the decimal point 

// console.log(balance.toPrecision(3)) // 122 ==> actully it work as round but differnt alot!!!*****
// /*  example:
// const aDigit = 23.894234;
// console.log(aDigit.toPrecision(2)) // 24
// console.log(aDigit.toPrecision(1)) // 2e+1

// const anotherDigit = 123.894234;
// console.log(aDigit.anotherDigit(4)) // 123.9

//                 for better understand search online!!!**********important
// */
// const aBigNumber = 100000000;
// console.log(aBigNumber.toLocaleString()) //100,000,000 here toLocaleString convert the big integer to easy

// // some function in Number:
// /*
// ƒ Number()
// ƒ toExponential()
// ƒ toFixed()
// ƒ toLocaleString()
// ƒ toPrecision()
// ƒ toString()
// ƒ valueOf()
// */

// // *******************************************MATHS***********************************************

// console.log(Math)
// console.log(Math.abs(-32)); //32
// console.log(Math.round(4.3)) //4
// console.log(Math.ceil(4.2)) //5
// console.log(Math.min(4,3,1,10,12,5,8,2)) //1

console.log(Math.random()); // here random is a function which print number always print number between 0 to 1 randomly

console.log((Math.random()*10)+1) // to move left of the first digit of decimail point generated by random function
// if in case of 0.0.... somthing generated by random function then
console.log(Math.floor((Math.random()*10)+1)); ///**********important*********//

const min = 10;
const max = 20;
console.log(Math.floor(Math.random()*(max - min + 1))+ min);

// some function in Maths
/* 
E = 2.718281828459045
LN2 = 0.6931471805599453
LN10 = 2.302585092994046
LOG2E = 1.4426950408889634
LOG10E = 0.4342944819032518
PI = 3.141592653589793
SQRT1_2 = 0.7071067811865476
SQRT2 = 1.4142135623730951

ƒ abs()
ƒ acos()
ƒ acosh()
ƒ asin()
ƒ asinh()
ƒ atan()
ƒ atan2()
ƒ atanh()
ƒ cbrt()
ƒ ceil()
ƒ clz32()
ƒ cos()
ƒ cosh()
ƒ exp()
ƒ expm1()
ƒ floor()
ƒ fround()
ƒ hypot()
ƒ imul()
ƒ log()
ƒ log1p()
ƒ log2()
ƒ log10()
ƒ max()
ƒ min()
ƒ pow()
ƒ random()
ƒ round()
ƒ sign()
ƒ sin()
ƒ sinh()
ƒ sqrt()
ƒ tan()
ƒ tanh()
ƒ trunc()

*/